Cmake build
ACCESS-NRI/MOM6 pull request #2
Opened 2024-12-09 04:11 UTC by minghangli-uni

Open this PR to make some minor tweaks visible.

2025-01-23 04:04 UTC, anton-seaice commented on cmake/MOM6libConfig.cmake.in
> +
find_dependency(NetCDF REQUIRED Fortran)

2025-01-23 06:12 UTC, minghangli-uni commented on cmake/CMakeLists.txt
> +    DESTINATION ${CMAKE_INSTALL_MODULEDIR}/mom6lib
```suggestion
    DESTINATION ${CMAKE_INSTALL_MODULEDIR}/MOM6lib
```

2025-02-05 03:34 UTC, anton-seaice commented on cmake/FindPIO.cmake
This file isn't used ( I hope)

2025-02-05 03:36 UTC, anton-seaice commented on cmake/MOM6libConfig.cmake.in
> +
```suggestion
if (NOT NetCDF_PARALLEL)
    message(FATAL_ERROR "NetCDF does not have parallel I/O support!")
endif()
```

2025-02-13 23:21 UTC, anton-seaice commented on cmake/CompilerFlags.cmake
I think you need to update this for "GNU" compiler too?

```
## MOM6 Fortran compiler flags
if(CMAKE_Fortran_COMPILER_ID MATCHES "GNU")
  set(fortran_compile_flags -fdefault-real-8 -fdefault-double-8)
elseif(CMAKE_Fortran_COMPILER_ID MATCHES "Intel")
```

@dougiesquire ?

https://github.com/COSIMA/access-om3/blob/a5ecf6b339049eb74b76dd6557c54b99edd3e28d/MOM6/CMakeLists.txt#L3C1-L6C50

2025-02-13 23:23 UTC, anton-seaice commented on cmake/CompilerFlags.cmake
Hangon, operator error, its already set

2025-02-13 23:40 UTC, dougiesquire commented on cmake/CompilerFlags.cmake
> +  set(CMAKE_Fortran_FLAGS "-fdefault-real-8 -fdefault-double-8")
@anton-seaice, you're right - missed this

```suggestion
  set(CMAKE_Fortran_FLAGS "${CMAKE_Fortran_FLAGS} -fbacktrace -fconvert=big-endian -ffree-line-length-none -ffixed-line-length-none -fdefault-real-8 -fdefault-double-8")
  if(${CMAKE_Fortran_COMPILER_VERSION} VERSION_GREATER_EQUAL 10)
    set(CMAKE_Fortran_FLAGS "${CMAKE_Fortran_FLAGS} -fallow-argument-mismatch")
  endif()
```

2025-02-13 23:41 UTC, dougiesquire commented on cmake/CompilerFlags.cmake
Nope - you're right: https://github.com/ACCESS-NRI/MOM6/pull/2#discussion_r1955355389

2025-03-20 03:37 UTC, anton-seaice commented
This is ready to review. This adds a CMake build for MOM6. The build supports building a [library](https://github.com/ACCESS-NRI/ACCESS-OM3/pull/35) with access3 dependencies and [building a standalone mom6](https://github.com/ACCESS-NRI/ACCESS-OM3/pull/64).

If you have time to review @micaeljtoliveira that would be great.

@dougiesquire please review and confirm which is the right target branch for this PR?

@minghangli-uni - please reivew too :)

FYI @chrisb13

2025-03-25 23:26 UTC, dougiesquire requested changes
Thanks @anton-seaice and @minghangli-uni. Looking great! One typo and a few questions, mostly about default settings.

Regarding which branch to use, I think it's probably best to use `dev/access`. There's an issue with the generic tracer changes that I need to resolve. We can still test most of our configs using `dev/access`, just not the WOMBAT one.

2025-03-25 23:26 UTC, dougiesquire commented on CMakeLists.txt
> +option(MOM_SYMMETRIC "Use MOM symmetric memory"                               OFF)
Can we rename this to `"SYMMETRIC"`? Having `"MOM"` in the name made sense for the monolithic build, but it seems redundant here.

I also note that the MOM6 autoconf system has the option `--enable-asymmetric`. If we're hoping to get the cmake system upstream it might make sense to align ourselves with their logic now, i.e. have an `ASYMMETRIC` option that for now defaults to OFF.

2025-03-25 23:26 UTC, dougiesquire commented on CMakeLists.txt
> +option(ACCESS3_MOM6  "Use ACCESS3 dependencies and install ACCESS3 libraries" ON )
I wonder if the default for this should be OFF. To me it seems logical that a component build system should build standalone by default. The is especially true if we're hoping to get this upstream.

2025-03-25 23:26 UTC, dougiesquire commented on CMakeLists.txt
> +endif()
I'm not sure I understand the justification for choosing which flags are set here and which are set at a higher level. There seems to be a longer list here than what's included by default with the MOM6 autoconf system.

2025-03-25 23:26 UTC, dougiesquire commented on CMakeLists.txt
> +add_compile_definitions(_USE_GENERIC_TRACER _USE_MOM6_DIAG)
No change needed now but at some point we may want to make this a configurable option

2025-03-25 23:26 UTC, dougiesquire commented on CMakeLists.txt
> +if(ENABLE_MOM_SYMMETRIC)
```suggestion
if(MOM_SYMMETRIC)
```

2025-03-25 23:30 UTC, micaeljtoliveira commented on CMakeLists.txt
> +option(ACCESS3_MOM6  "Use ACCESS3 dependencies and install ACCESS3 libraries" ON )
I would second that.

2025-03-25 23:35 UTC, micaeljtoliveira commented on CMakeLists.txt
> +option(MOM_SYMMETRIC "Use MOM symmetric memory"                               OFF)
> Can we rename this to "SYMMETRIC"? Having "MOM" in the name made sense for the monolithic build, but it seems redundant here.

Actually, CMake good practices would suggest to **add** the prefix to all options. This make it easier to build a CMake project from another CMake project. This is not something we are doing at ACCESS-NRI, but other groups might want to do it.

2025-03-25 23:37 UTC, minghangli-uni commented on CMakeLists.txt
> +option(ACCESS3_MOM6  "Use ACCESS3 dependencies and install ACCESS3 libraries" ON )
I agree with that too. Would it be clearer to users if we added an explanation as a comment just before or inside the optio, e.g., 
```suggestion
# Default is OFF to support standalone builds
option(ACCESS3_MOM6  "Use ACCESS3 dependencies and install ACCESS3 libraries" OFF )
```

2025-03-25 23:43 UTC, dougiesquire commented on CMakeLists.txt
> +option(MOM_SYMMETRIC "Use MOM symmetric memory"                               OFF)
Okay, good to know. So we could have?
```
option(MOM6_ACCESS3    "Use ACCESS3 dependencies and install ACCESS3 libraries" OFF)
option(MOM6_OPENMP     "Enable OpenMP threading"                                OFF)
option(MOM6_ASYMMETRIC "Use MOM asymmetric memory"                              OFF)
```

2025-03-25 23:46 UTC, dougiesquire commented on CMakeLists.txt
> +    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR} COMPONENT AccessMOM6Cmeps_runtime NAMELINK_COMPONENT AccessMOM6Cmeps_Development
(This comment somehow didn't get included in my previous review, so reposting)

For my own learning, why is `NAMELINK_COMPONENT` needed here?

Also, could these names be shorter? Do we really need `"Cmeps"` in the name? What is the significance of the `"_Development"`?

2025-03-25 23:51 UTC, micaeljtoliveira commented on CMakeLists.txt
> +endif()
These flags were the ones used to build MOM6 in CESM, but this is not necessarily what we want going forward.

There are two types of flags that should go here:
- flags that are **necessary** for the code to work correctly (e.g., `-fdefault-real-8`)
- flags that are **recommended** for production and/or debug (e.g., `-O`, `-Wall`)

Users can then either append other flags or they can overwrite them entirely at their own risk.

This is a bit different from how this is normally set up in autotools based build systems (took me a while to get my head around this), so I wouldn't necessarily model it on the existing MOM6 autoconf system.

2025-03-25 23:56 UTC, minghangli-uni commented on CMakeLists.txt
> +    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR} COMPONENT AccessMOM6Cmeps_runtime NAMELINK_COMPONENT AccessMOM6Cmeps_Development
My understanding is `NAMELINK_COMPONENT` tells cmake to place symbolic links of AccessMOM6Cmeps_runtime to a separate place, in this case, AccessMOM6Cmeps_Development, which I think is used for development purpose. 

I think Cmeps follows the @micaeljtoliveira's configuration in COSIMA access-om3

_Development is just a conventional suffix, which is used to link and build but not for execution.

2025-03-26 00:02 UTC, dougiesquire commented on CMakeLists.txt
> +    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR} COMPONENT AccessMOM6Cmeps_runtime NAMELINK_COMPONENT AccessMOM6Cmeps_Development
> My understanding is NAMELINK_COMPONENT tells cmake to place symbolic links of AccessMOM6Cmeps_runtime to a separate place, in this case, AccessMOM6Cmeps_Development, which I think is used for development purpose.

Thanks @minghangli-uni. Yeah, I read what it does, but I still don't think I understand why it's needed.

> I think Cmeps follows the @micaeljtoliveira's configuration in COSIMA access-om3

Hmmm, I [don't think so](https://github.com/COSIMA/access-om3/blob/58e40cb4381b094be739f408329ae0eaaaa99882/MOM6/CMakeLists.txt#L394-L395):

```
    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR} COMPONENT AccessOM3_RunTime NAMELINK_COMPONENT AccessOM3_Development
    ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR} COMPONENT AccessOM3_Development
```

2025-03-26 00:08 UTC, minghangli-uni commented on CMakeLists.txt
> +    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR} COMPONENT AccessMOM6Cmeps_runtime NAMELINK_COMPONENT AccessMOM6Cmeps_Development
> Thanks @minghangli-uni. Yeah, I read what it does, but I still don't think I understand why it's needed.

It depends on the target groups. For end users, they only need the runtime component. I’m not entirely sure how the developer requirements are managed, probably @micaeljtoliveira would be better to comment this.

2025-03-26 00:23 UTC, micaeljtoliveira commented on CMakeLists.txt
> +    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR} COMPONENT AccessMOM6Cmeps_runtime NAMELINK_COMPONENT AccessMOM6Cmeps_Development
> For my own learning, why is NAMELINK_COMPONENT needed here?

First of all, it's important to note that artifacts of type `LIBRARY` are shared libraries on Linux. We haven't introduced the option to build shared libraries here yet, but doesn't hurt to set all these options correctly from the start ;)
  
When installing a shared library on Linux one also creates a symbolic link to the soname of the library:

`lib<name>.so -> lib<name>.so.1`

which is usually used at compile time. Here, `NAMELINK_COMPONENT` refers to that symbolic link.

>  What is the significance of the "_Development"?

CMake allow you to distinguish between components that are needed at runtime (for example an executable or a shared library) from components that are needed at build time (for example a static library). Convention is to name the former "Runtime" and the later as "Development" .

So, here we are basically telling CMake that, when the `mom6lib` target is a shared library, it should be installed to  `${CMAKE_INSTALL_LIBDIR}`, that the library itself is a component needed at runtime and the name link is a component needed at build time. Makes sense?

> Also, could these names be shorter? Do we really need "Cmeps" in the name?

No strong opinion on keeping or not "Cmeps" in the name. The `Access` prefix is probably enough to avoid name clashes, so should not hurt to remove it.

2025-03-26 00:27 UTC, anton-seaice commented on CMakeLists.txt
> +endif()
This should be the only place we have the set currently. You can also set them in spack but it's very easy to end up in a mess that way. 

Is it ok if we bump this to a new issue? These flags should be the same as the ones set in https://github.com/cOSIMA/access-om3 , and this needs a review of all components, confirming which flags are needed and then also optimising for performance.

2025-03-26 00:28 UTC, anton-seaice commented on CMakeLists.txt
> +add_compile_definitions(_USE_GENERIC_TRACER _USE_MOM6_DIAG)
Yes I think it's easy enough to add later without breaking any current behaviour

2025-03-26 00:28 UTC, minghangli-uni commented on CMakeLists.txt
> +option(MOM_SYMMETRIC "Use MOM symmetric memory"                               OFF)
I agree. `MOM6_ASYMMETRIC ` would be better.

2025-03-26 00:31 UTC, minghangli-uni commented on CMakeLists.txt
> +add_compile_definitions(_USE_GENERIC_TRACER _USE_MOM6_DIAG)
I’m sorry if I’m misunderstanding, but if this change is going to happen someday, why not implement it now?

2025-03-26 00:34 UTC, micaeljtoliveira commented on CMakeLists.txt
> +option(MOM_SYMMETRIC "Use MOM symmetric memory"                               OFF)
> Okay, good to know. So we could have?
> 
> ```
> option(MOM6_ACCESS3    "Use ACCESS3 dependencies and install ACCESS3 libraries" OFF)
> option(MOM6_OPENMP     "Enable OpenMP threading"                                OFF)
> option(MOM6_ASYMMETRIC "Use MOM asymmetric memory"                              OFF)
> ```

Yes. Probably should also rename `CESMCOUPLED` to `MOM6_CESMCOUPLED`.

Just to explain this further, the reason why one wants to have options with unique names is so that users can set them all separately.  Imagine you have a CMake project that builds both MOM6 and WW3. The users of that package might want to compile MOM6 with OpenMP, but WW3 without it (I don't know if WW3 uses OpenMP, but let's assume it does). There's not easy way to do it if both MOM6 and WW3 expose an option with the same name.

2025-03-26 00:38 UTC, anton-seaice commented
> Regarding which branch to use, I think it's probably best to use `dev/access`. There's an issue with the generic tracer changes that I need to resolve. We can still test most of our configs using `dev/access`, just not the WOMBAT one.

ok - we'd want to reset `dev/access` to the same as  branch 'origin/PRcandidate-202502-gtracer-nuopc' first to avoid the unrelated changes being in this PR.

I thought `dev/access` needs to be in a state to be able to merge upstream in the future ? (which it wouldn't be with this change)

2025-03-26 00:50 UTC, anton-seaice commented on CMakeLists.txt
> +add_compile_definitions(_USE_GENERIC_TRACER _USE_MOM6_DIAG)
I'm trying to minimise adding options for "we may want this one day" to reduce complexity (which add testing and risk etc)

2025-03-26 01:11 UTC, dougiesquire commented on CMakeLists.txt
> +    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR} COMPONENT AccessMOM6Cmeps_runtime NAMELINK_COMPONENT AccessMOM6Cmeps_Development
Thanks for that detailed explanation @micaeljtoliveira!

2025-03-26 01:13 UTC, dougiesquire commented
> ok - we'd want to reset dev/access to the same as branch 'origin/PRcandidate-202502-gtracer-nuopc' first to avoid the unrelated changes being in this PR.

I don't think we want to do this

> I thought dev/access needs to be in a state to be able to merge upstream in the future ? (which it wouldn't be with this change)

I need to go and reread the new fork-management policy

2025-03-26 01:18 UTC, dougiesquire commented on CMakeLists.txt
> +find_package(fms COMPONENTS R8 REQUIRED)
Just a note that I think [MOM6 requires FMS 2019.01.02 or newer](https://github.com/mom-ocean/MOM6/blob/e818ea4e792f0b85797247f955789b3c1210db8d/ac/configure.ac#L211-L224), though it's probably not worth trying to enforce this.

2025-03-26 04:10 UTC, anton-seaice commented on CMakeLists.txt
> +option(MOM_SYMMETRIC "Use MOM symmetric memory"                               OFF)
Im 100% sure you are correct - but I don't quite understand this usecase.

This CMakeList file defines a project already, and if I build MOM6 and WW3 in seperate projects, there's no namespace clash (I think). I can then find them in a different project through a `find_package()` call

Are you saying its possible to define a different cmake project which would build MOM6 using this CMakeLists file but be a different project ? (e.g. using `ExternalProject()` in [cmake](https://cmake.org/cmake/help/v3.31/module/ExternalProject.html)?)

2025-03-26 04:17 UTC, micaeljtoliveira commented on CMakeLists.txt
> +option(MOM_SYMMETRIC "Use MOM symmetric memory"                               OFF)
> Are you saying its possible to define a different cmake project which would build MOM6 using this CMakeLists file but be a different project ? (e.g. using `ExternalProject()` in [cmake](https://cmake.org/cmake/help/v3.31/module/ExternalProject.html)?)

Yes, exactly. `FetchContent` is becoming a very powerful and popular approach to include dependencies in CMake and, although we are not planning on using this feature at ACCESS-NRI, other people might. And since there's the ambition to have this CMake build system included upstream, better to follow best practices.

2025-03-26 04:20 UTC, anton-seaice commented on CMakeLists.txt
> +endif()
See https://github.com/ACCESS-NRI/ACCESS-OM3/issues/73

2025-03-26 05:06 UTC, anton-seaice commented on CMakeLists.txt
> +find_package(fms COMPONENTS R8 REQUIRED)
The first CMake build appears to be 2020.02

https://github.com/NOAA-GFDL/FMS/commit/6242dfeb066a209e4d4aad82235c54ee092857ae

2025-03-26 05:08 UTC, dougiesquire commented on CMakeLists.txt
> +find_package(fms COMPONENTS R8 REQUIRED)
Never mind then :)

2025-03-27 02:06 UTC, anton-seaice commented on CMakeLists.txt
> +option(MOM_SYMMETRIC "Use MOM symmetric memory"                               OFF)
Okie - i made the change to use MOM6 prefix everywhere and to flipped the option to be ASYMMETRIC default OFF

2025-03-27 02:07 UTC, anton-seaice commented on CMakeLists.txt
> +option(ACCESS3_MOM6  "Use ACCESS3 dependencies and install ACCESS3 libraries" ON )
change this to default OFF

2025-03-27 02:07 UTC, anton-seaice commented on CMakeLists.txt
> +if(ENABLE_MOM_SYMMETRIC)
Done / superseeded by other changes

2025-03-27 02:07 UTC, anton-seaice commented on CMakeLists.txt
> +    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR} COMPONENT AccessMOM6Cmeps_runtime NAMELINK_COMPONENT AccessMOM6Cmeps_Development
Okay i dropped Cmeps from the naems

2025-03-27 02:09 UTC, anton-seaice commented
Apologies for the git chaos.

Even though this change won't end up upstream (probably), we will merge into `dev/access` - as described in #7 

I removed the generic tracers changes which are not in `dev/access` yet.

2025-03-27 03:19 UTC, anton-seaice commented
I think I addressed all the comments. This is ready for re-review

New builds:

https://github.com/ACCESS-NRI/ACCESS-OM3/pull/35#issuecomment-2756448111
https://github.com/ACCESS-NRI/ACCESS-OM3/pull/64#issuecomment-2756319322

2025-03-27 03:24 UTC, micaeljtoliveira submitted a review, later dismissed
LGTM!

2025-03-27 03:35 UTC, dougiesquire commented on CMakeLists.txt
> +  option(MOM6_CESMCOUPLED "Use CESMCOUPLED"                                     OFF)
I can't remember whether I'm now contradicting myself or not but...

Should this default to ON, given that it's only available with `MOM6_ACCESS3`?

2025-03-27 03:40 UTC, anton-seaice commented on CMakeLists.txt
> +  option(MOM6_CESMCOUPLED "Use CESMCOUPLED"                                     OFF)
I think i was optimistic the need for this would get removed one day ??

And I kind of like that by forcing users to set it they know its on.

2025-03-27 03:45 UTC, dougiesquire commented on CMakeLists.txt
> +  option(MOM6_CESMCOUPLED "Use CESMCOUPLED"                                     OFF)
Yeah fair. So are you thinking this will be set in the `spack.yaml`?

2025-03-27 03:47 UTC, anton-seaice commented on CMakeLists.txt
> +  option(MOM6_CESMCOUPLED "Use CESMCOUPLED"                                     OFF)
It's currently set in the `access3-exe` package. Not sure if I like that idea or not

2025-03-27 03:49 UTC, micaeljtoliveira commented on CMakeLists.txt
> +  option(MOM6_CESMCOUPLED "Use CESMCOUPLED"                                     OFF)
This raises an interesting question: what happens if one tries to build OM3 with an installation of MOM6 that was compiled with `MOM6_CESMCOUPLED = OFF`? I guess OM3 would compile, right?

2025-03-27 03:51 UTC, anton-seaice commented on CMakeLists.txt
> +  option(MOM6_CESMCOUPLED "Use CESMCOUPLED"                                     OFF)
I think CICE doesn't compile at all.

I'm not sure about MOM ... ill try it now

2025-03-27 03:56 UTC, micaeljtoliveira commented on CMakeLists.txt
> +  option(MOM6_CESMCOUPLED "Use CESMCOUPLED"                                     OFF)
Thanks for checking this. If compilation fails, this is not too bad, because at least users won't get a wrong executable to run. But might be worth considering adding some safeguards.

2025-03-27 03:57 UTC, anton-seaice commented on CMakeLists.txt
> +  option(MOM6_CESMCOUPLED "Use CESMCOUPLED"                                     OFF)
Appears to build fine with this OFF

2025-03-27 04:01 UTC, dougiesquire commented on CMakeLists.txt
> +  option(MOM6_CESMCOUPLED "Use CESMCOUPLED"                                     OFF)
It won't work in ACCESS-OM3 though right? So should we ensure that `MOM6_CESMCOUPLED = ON` when `MOM6_ACCESS3 = ON`?

2025-03-27 04:05 UTC, anton-seaice commented on CMakeLists.txt
> +  option(MOM6_CESMCOUPLED "Use CESMCOUPLED"                                     OFF)
> It won't work in ACCESS-OM3 though right?

It appears to build. Not sure it runs.

2025-03-27 04:07 UTC, anton-seaice commented on CMakeLists.txt
> +  option(MOM6_CESMCOUPLED "Use CESMCOUPLED"                                     OFF)
I think build with the nuopc driver and cesmcoupled off is a valid way to use MOM right? Its just not the way we use it

2025-03-27 04:07 UTC, dougiesquire commented on CMakeLists.txt
> +  option(MOM6_CESMCOUPLED "Use CESMCOUPLED"                                     OFF)
I'd be very surprised if it did.

2025-03-27 04:09 UTC, dougiesquire commented on CMakeLists.txt
> +  option(MOM6_CESMCOUPLED "Use CESMCOUPLED"                                     OFF)
> I think build with the nuopc driver and cesmcoupled off is a valid way to use MOM right? Its just not the way we use it

Yeah it is, but it's not really valid for OM3. The coupled fields are different for example

2025-03-27 04:14 UTC, anton-seaice commented on CMakeLists.txt
> +  option(MOM6_CESMCOUPLED "Use CESMCOUPLED"                                     OFF)
I think leaving the option available and setting in spack is ok then?

Maybe default should be ON, one less thing for us to forget if using Cmake directly ?

2025-03-27 04:14 UTC, micaeljtoliveira commented on CMakeLists.txt
> +  option(MOM6_CESMCOUPLED "Use CESMCOUPLED"                                     OFF)
Maybe one should clarify what `MOM6_ACCESS3 = ON` means. If it just means to build with NUOPC coupling, then one should allow `MOM6_CESMCOUPLED = OFF` (and probably rename `MOM6_ACCESS3` to something else). If it means build for use in OM3, then probably `MOM6_CESMCOUPLED` should always be `ON` (in which case better to simply remove the option).

2025-03-27 04:17 UTC, anton-seaice commented on CMakeLists.txt
> +  option(MOM6_CESMCOUPLED "Use CESMCOUPLED"                                     OFF)
I guess even if someone else builds with nuopc coupling using cmeps/cdeps and share, its highly unlikely that they would use https://github.com/accESS-NRI/access3-share ?

I think you've convinced me - ill remove the option

2025-03-27 04:21 UTC, dougiesquire approved these changes, later dismissed
LGTM!

2025-03-27 22:35 UTC, anton-seaice commented
This is ready to merge, just holding off until we are tripley sure `dev/access` is the place for it

2025-03-31 04:33 UTC, dougiesquire reviewed
Sorry, another thought:

I wonder if we should put `CMakeLists.txt` in the `cmake` directory. This might be preferred if/when we try to get this upstream.

2025-03-31 04:39 UTC, anton-seaice commented
I figure we can change that later if desired. The base directory is the default / standard location

2025-05-06 02:40 UTC, dougiesquire commented
@anton-seaice, please feel free to merge this now (squash?)

2025-05-06 03:20 UTC, dougiesquire reviewed
Good catch

2025-05-06 03:21 UTC, dougiesquire approved these changes

2025-05-06 03:28 UTC, merged